# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Plugin-Cache
version:      0.03
version_from: lib/WWW/Mechanize/Plugin/Cache.pm
installdirs:  site
requires:
    Cache::FileCache:              0
    Data::Dump::Streamer:          0
    Test::Exception:               0
    Test::More:                    0
    WWW::Mechanize::Pluggable:     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
